Allow GET endpoint to use URL params instead of body
RedMser/discotron pull request #2
Opened 2020-03-21 22:00 UTC by Blatoy

2020-03-21 23:01 UTC, RedMser requested changes

2020-03-21 23:01 UTC, RedMser commented on dashboard/backend/api.js
> +            appToken = authorizationHeader.slice(7);
Write a comment describing where the magic number 7 comes from.

2020-03-21 23:01 UTC, RedMser commented on dashboard/backend/api.js
> +                reply({ status: 400, error: new WebApiError("GET endpoint excepts values to be JSON encoded", "get-params-not-json-encoded"), source: "core" });
If easily possible, include the value of both `key` and `req.query[key]` in this error, so it's easy to know what caused the error.

2020-03-21 23:01 UTC, RedMser commented on dashboard/backend/api.js
> +            console.log("IN ENDPOINT");
:eyes:

2020-03-21 23:01 UTC, RedMser commented on dashboard/backend/api.js
> +        const authorizationHeader = req.header("authorization");
Uppercase **A** to be consistent with other HTTP headers and client code.

2020-03-21 23:01 UTC, RedMser commented on dashboard/www/scripts/utils/utils.js
> +            return await response.json();
Shouldn't this try block extend up to the `fetch` as well?

2020-03-21 23:01 UTC, RedMser commented on dashboard/www/scripts/utils/utils.js
> +            throw new discotron.WebApiError("An error occurred when communicating with the bot. Status code: " + response.status);
I'm kind of against using a WebApiError in a general `utils` function. Even though it's ugly and annoying, we should possibly re-catch on the calling side, and use a regular `Error` type here?

2020-03-21 23:01 UTC, RedMser commented on dashboard/www/scripts/utils/utils.js
>       * @param {object} [body] Data that will be JSON.stringified and sent to the website. Does not work for GET requests.
Update this to reflect what happens for GET.

2020-03-23 01:41 UTC, Blatoy commented on dashboard/backend/api.js
> +            console.log("IN ENDPOINT");
:eyes:

2020-03-26 00:16 UTC, RedMser requested changes

2020-03-26 00:16 UTC, RedMser commented on dashboard/www/scripts/web-api.js
> +window.onerror = (a, b, c, d, e) => {
:eyes: 💦

2020-03-27 00:39 UTC, merged